### ISSUE TITLE
Add New Terms

### ISSUE THREAD

**Issue by ruthtillman** [Art-and-Rare-Materials-BF-Ext/arm#1]
Using the https://docs.google.com/spreadsheets/d/1G9gcsVrOWJz8ZFMMgHpHddy6M0jsD29aRFg2ZfXmKDk/edit spreadsheet, add the following Classes and Properties. Record progress in the "Status" column of the spreadsheet.

Classes:

- [x] arm:Annotation
- [x] arm:Bookplate
- [x] arm:Event
- [x] arm:ItemHistory

Properties:

- [x] arm:hasRelatedEvent
- [x] arm:hasType
- [x] arm:physicalPresentation

**Comment by regineheberlein** [comment]
Also, add RDA replacements for deprecated properties:

- [ ] http://rdaregistry.info/Elements/u/P60995
- [ ] http://rdaregistry.info/Elements/u/P60596
- [ ] http://rdaregistry.info/Elements/u/P60159

deprecated:
 arm:hasMaterial
 arm:isMaterialOf
 arm:isBaseMaterialOf
 arm:isAppliedMaterialOf

**Comment by regineheberlein** [comment]
Question: Is this editorial remark our default for all arm: classes?
<skos:editorialNote xml:lang="en">Deprecate this class when it is defined in BIBFRAME.</skos:editorialNote>

**Comment by regineheberlein** [comment]
Question: Is this ok for definition on Event? (The spreadsheet only says "generic event class".) Paraphrasing/condensing language I grabbed from the notes document:

"Optional mechanism to provide granular documentation of events on resources. May include conservation activities, exhibits, provenance information, or physical condition."

**Comment by regineheberlein** [comment]
Question: Is this ok for definition on ItemHistory? Paraphrasing/condensing language from the spreadsheet and notes doc:

"Optional superclass to gather all events for a resource together as needed."

**Comment by regineheberlein** [comment]
Can I get some guidance on moving the above object properties to the rda namespace (https://docs.google.com/document/d/1GHoS9TIYbQiM83dAgRMm-ZZr1COOhGemfGQlEALMWRk/edit): 

Are we literally editing the existing object properties that correspond to these three rda properties (e.g. changing the @rdf:about), and removing the rest? If not, what exactly needs to be done?

**Comment by jak473** [comment]
> Question: Is this editorial remark our default for all arm: classes?
> <skos:editorialNote xml:lang="en">Deprecate this class when it is defined in BIBFRAME.</skos:editorialNote>

@regineheberlein : from my POV, we'd only add that if we believe that the term is one that should be in BF rather than ARM, e.g.: AccessionNumber. For most of ARM, this would not apply.

**Comment by jak473** [comment]
> Question: Is this ok for definition on Event? (The spreadsheet only says "generic event class".) Paraphrasing/condensing language I grabbed from the notes document:
> 
> "Optional mechanism to provide granular documentation of events on resources. May include conservation activities, exhibits, provenance information, or physical condition."

We should run past the ARM group; can do so via email.

**Comment by jak473** [comment]
> Question: Is this ok for definition on ItemHistory? Paraphrasing/condensing language from the spreadsheet and notes doc:
> 
> "Optional superclass to gather all events for a resource together as needed."

We should run past the ARM group; can do so via email.

**Comment by jak473** [comment]
> Can I get some guidance on moving the above object properties to the rda namespace (https://docs.google.com/document/d/1GHoS9TIYbQiM83dAgRMm-ZZr1COOhGemfGQlEALMWRk/edit):
> 
> Are we literally editing the existing object properties that correspond to these three rda properties (e.g. changing the `@rdf:about`), and removing the rest? If not, what exactly needs to be done?

Just to confirm, you mean the RDA terms for hasMaterial; hasAppliedMaterial; and hasBase. These can be omitted from the ontology update work; instead, the usage guidelines and (possibly) other documentation will reference the reuse of these terms.

**Comment by rdesmeules** [comment]
> 
> 
> Question: Is this ok for definition on ItemHistory? Paraphrasing/condensing language from the spreadsheet and notes doc:
> 
> "Optional superclass to gather all events for a resource together as needed."

Yes, I think this works.

**Comment by mlhale7** [comment]
I had a tiny edit removing an extra "g" in the skos:definition of physcialPresentation. I've commented on the line in the PR. Otherwise I am happy to sign off on this issue.

**Comment by regineheberlein** [comment]
Good catch everyone re: the double “g”! Fixed and merged.

Regine Heberlein
Library IT Data Analyst
609-258-6156
heberlei@princeton.edu

**Comment by timathom** [comment]
> > Question: Is this ok for definition on ItemHistory? Paraphrasing/condensing language from the spreadsheet and notes doc:
> > "Optional superclass to gather all events for a resource together as needed."
> 
> We should run past the ARM group; can do so via email.

@jak473 I don't think these definitions (Event and ItemHistory) were followed up on via e-mail--unless I missed it.

**Comment by rdesmeules** [comment]
Agreed, they were not. There are also some outstanding questions with the Exhibitions model that may impact these definitions - is email the best forum to catch everyone at this point? Or should this be on the docket for Monday's meeting?

**Comment by regineheberlein** [comment]
Indeed, I was waiting to see whether we needed to discuss other definitions. At this point, I think it’d be more efficient to discuss at the meeting?

Regine Heberlein
Library IT Data Analyst
609-258-6156
heberlei@princeton.edu
