### ISSUE TITLE
Review and reorganize repository

### ISSUE THREAD

**Issue by ruthtillman** [Art-and-Rare-Materials-BF-Ext/arm#18]
Because we forked and edited this repository, we should review and reorganize as appropriate.

Use this issue to note areas which should be reviewed and areas which we already know (or think) should be deleted.

**Comment by ruthtillman** [comment]
arm/custodial_history/ will be deleted yes?

what about arm/award?

**Comment by jak473** [comment]
Agreed that reorganization is needed. Two options immediately come to mind: 1. top-level division b/t version 0.1 and version 1.0 OR top-level division b/t ontology file(s) and background documents.

Also should add an easy-to-view change log

**Comment by ruthtillman** [comment]
I like the idea of top-level versioning division -- would love to hear if others see issues with that.

And definitely change log.

**Comment by jak473** [comment]
My vote: +1 to top-level versioning division

**Comment by jak473** [comment]
Since this came up in this discussion, will post the link here. Change log (first pass, rough draft): https://github.com/Art-and-Rare-Materials-BF-Ext/arm/blob/master/changelog.md

**Comment by timathom** [comment]
I like the idea of top-level versioning, but it does break the symmetry between repo structure and URI structure. The 0.1 URIs mimic the repo folder structure: prefix (https://w3id.org/) + `arm/core/ontology/0.1/`. But I don't think this should create any technical problems.

I'd recommend keeping the top-level folder names short: rather than `version 1.0` (generally avoiding spaces in file/folder names), just `1.0` or `v1.0`. I'd also recommend keeping conventions aligned as much as possible between versions: so, `1.0/ontology/1.0/arm.rdf` for the new version.

**Comment by jak473** [comment]
I'm good with shortening the names to v1.0/v0.1. 

The 0.1 LD4P repo had significantly more content than 1.0 will have, including divided ontology files; as a result, the structure in that directory is highly/overly complex for what 1.0 would demand. What do others think about mimicking directory structure between the two versions?

**Comment by timathom** [comment]
Good point about complexity. But having `ontology` as a subfolder still seems to make sense, since we'll have other kinds of artifacts as well. I think we could remove `1.0` from the path, since it's now redundant given the top-level structure.

**Comment by mlhale7** [comment]
I agree with pursuing top-level versioning as I think the division between 0.1 and 1.0 is cleanest/intuitive this way and it keeps a good record. I also agree with continuing to have an ontology folder. I would second Tim that we don't need "version" in front of the number.

**Comment by jak473** [comment]
Sounds good. Perhaps the easiest approach is to merge current reorg and then do another PR to update based on @timathom and @mlhale7 's comments.
