### ISSUE TITLE
Remove Complex Deprecations

### ISSUE THREAD

**Issue by ruthtillman** [Art-and-Rare-Materials-BF-Ext/arm#3]
The spreadsheet https://docs.google.com/spreadsheets/d/1G9gcsVrOWJz8ZFMMgHpHddy6M0jsD29aRFg2ZfXmKDk/edit indicates that these deprecations may involve substituting an RDA term or otherwise be more complex to perform. Record progress in the "Status" column of the spreadsheet. 

- [x] arm:Activity and related subclasses
- [x] bf:arrangement / bf:Arrangement
- [x] arm:hasMaterial
- [x] arm:isMaterialOf
- [x] arm:isBaseMaterialOf
- [x] arm:isAppliedMaterialOf

**Comment by regineheberlein** [comment]
question re: bf:arrangement

Looking at the spreadsheet, this change affects the application profile. I'm looking at bibframe.2017-03-15_target.2.rdf, where it is already commented out. Am I looking in the wrong place?

**Comment by regineheberlein** [comment]
Note to self -- activity and related subclasses leaves behind two object properties, isActivityOf/hasActivity

**Comment by ruthtillman** [comment]
@regineheberlein re: arrangement -- it might. I realized after going through the spreadsheet that I was taking out the _only_ application profile ones manually and I might've missed a few.

**Comment by jak473** [comment]
Right; bf:arrangement/bf:Arrangement pertains to ARM stopping use of this property/class; instead we'll use arm:physicalPresentation for this.
